[package]
name = "abyssal-eclipse"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
gl = "0.14.0"
nalgebra-glm = "0.19.0"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"] }
image = "0.25.2"
